name: CI
on:
  push:
    branches:
      - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build
      - run: npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting --non-interactive
